version: 2.1

jobs:
  build-1:
    docker:
      - image: circleci/node:8.9.1

    steps:
      - checkout

      - run: npm install
      - run: make test-coverage-1

workflows:
  test:
    jobs:
      - build-1:
        filters:
            tags:
              only: /^v.*/