version: 2.1

jobs:
  build-1:
    docker:
      - image: circleci/node:14

    steps:
      - checkout

      - node/with-cache:
          steps:
            - run: npm install
            - run: make test-coverage-1

      - coveralls/upload:
          parallel: true
          flag_name: Test 1
          verbose: true

workflows:
  test_parallel_then_upload:
    jobs:
      - build-1